name: Aggiorna Podcast

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '25 18 * * 5'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install requirements
      run: pip install -r requirements.txt
    - name: Get the data and analyze
      run: |
        chmod +x ./podgen.py
        ./podgen.sh
      shell: bash
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Aggiornato feed podcast: ${timestamp}" || exit 0
        git push
